ALTER TABLE t_p80499285_psot_realization_pro.zdravpunkt_files
ADD COLUMN IF NOT EXISTS period_from DATE,
ADD COLUMN IF NOT EXISTS period_to DATE,
ADD COLUMN IF NOT EXISTS new_rows INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS skipped_rows INTEGER DEFAULT 0;
